version: '3.5'

services:
  dd-agent:
    image: datadog/agent-dev:6-5-0-rc-3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /Users/gregzussa/dd/integrations-core/istio/testing/scenario_1/conf.d:/conf.d:ro
    environment:
      - DD_API_KEY=11111111111111111111111111111111

